name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
      
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Rustfmt install
      run: rustup component add rustfmt
      
    - name: Rustfmt check
      run: cargo fmt -- --check
      
    - name: Clippy install
      run: rustup component add clippy
   
    - name: Clippy check
      run: cargo clippy -- -D warnings
        
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
          version: '0.15.0'
          args: '-- --test-threads 1'

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
    
